config/routes.rb
Rails.application.routes.draw do
  #root route
  root 'static_pages#home'
  # get 'static_pages/home'
  # get 'static_pages/about'
  # get 'pages/index'
  # get 'pages/show'
  # get 'pages/new'

  #custom route
  get '/about', to: 'static_pages#about'

  #generates crud action routes in this case for pages
  resources :pages
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/page.rb
class Page < ApplicationRecord
    #instance method
    def info
        return "Hello I am #{self.author} and your are reading #{self.body}"
    end
    #class method
    def self.custom_sql_call
        return "do custom stuff here"
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  #just grab all pages (generally for crud but not all the time)
  def index
    @pages = Page.all
    #rails convention... if you dont explicitly tell rails what to return here
    #it will automatically look in views/pages/index.html.erb and return that
  end

  #just grab one page
  def show
    @page = Page.find(params[:id])
    #it will automatically look in views/pages/show.html.erb 
  end

  def new
    #.new just makes a new page object in memory 
    #.create store to database
    @page = Page.new
  end
  def create
    @page = Page.new(pages_params)

    # this is always go work for now
    if @page.save
      redirect_to pages_path
    else
      # might have validations like must be present
      # we return user to the new form
      render :new
    end
  end
  
  def edit
    #return form here
    @page = Page.find(params[:id])
  end

  def update
    @page = Page.find(params[:id])

    if @page.update(pages_params)
      redirect_to pages_path
    else
      render :edit
    end
  end

  def destroy
    page = Page.find(params[:id])
    page.destroy
    redirect_to pages_path
  end

  private

  def pages_params
    params.require(:page).permit(:title, :author, :body)
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_navbar.html.erb
<%= link_to "Home", root_path%>
<%= link_to "About", about_path%>
<%= link_to "Pages", pages_path%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HelloWorldRails</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render 'layouts/navbar'%>
    <%= yield %>
  </body>
</html>

app/views/pages/edit.html.erb
<h1>Edit Form</h1>
<%= form_for @page do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :author %>
  <%= f.text_field :author %>

  <%= f.label :body %>
  <%= f.text_area :body %>

  <%= f.submit %>
<% end %>

app/views/pages/index.html.erb
<h1>Pages</h1>
<p>pages here</p>
<%= link_to 'new page', new_page_path %>
<%# this is my loop % ar non echoing %>

<% @pages.each do |page| %>
  <h2><%= page.title%></h2>
  <%= link_to 'Show Page',  page_path(page)%>
  <%= link_to 'Edit Page', edit_page_path(page)%>
  <%= link_to 'Delete Page', page_path(page), method: :delete%>
<% end %>

<%# @pages.each do |page|
 # do stuf on page
end %>

app/views/pages/new.html.erb
<h1>Pages#new</h1>
<p>Find me in app/views/pages/new.html.erb</p>

app/views/pages/show.html.erb
<h1>Pages</h1>
<h1><%= @page.title %> </h1>
<h3><%= @page.author %> </h3>
<p><%= @page.body %></p>
<%= link_to 'back to pages', pages_path %>

app/views/static_pages/about.html.erb
<h1>StaticPages#about</h1>
<p>Find me in app/views/static_pages/about.html.erb</p>

app/views/static_pages/home.html.erb
<h1>StaticPages#home</h1>
<p>Find me in app/views/static_pages/home.html.erb</p>